### ISSUE TITLE
[Bug] FoundryVTT Trick Weapons, can't add/label forms for a new trick weapon

### ISSUE THREAD

**Issue by Auxent1us** [trioderegion/steinhardts-support-desk#27] opened 2024-01-22 19:06 UTC
**Describe the bug**
When you make a new trick weapon in foundry it adds the trick weapon to the items tab however when clicking on the newly made Trick Weapon it won't open up the trick weapon leaving it blank and unable to access.

**Does this occur with all other modules disabled? If not, list minimum required module set to reproduce issue.**
 * Yes

**To Reproduce**
1. Go to 'Items tab'
2. Click on 'create item'
3. Scroll down to 'trick weapon'
4. Create trick weapon
5. Double click on trick weapon
6. Bug

**Expected behavior**
After double clicking on the newly created trick weapon you should be able top add/label new forms to the trick weapon.

**Recording**

(Removed for copyright-violating materials)

**System Information (please complete the following information):**
 - Foundry Version: V11.315
 - dnd5e System Version 2.4.1

**Additional context**

**Comment by trioderegion** [comment] 2024-01-22 19:10
It looks like there are multiple modules enabled. Including some that I provide zero support for in the presence of SGEH.  If you can reproduce this without other modules (especially those that violate copyright law), I can look into it.

**Comment by trioderegion** [comment] 2024-01-22 19:28
Closed as TidySheet5e bug.

**Closed by trioderegion** 2024-01-22 19:28 UTC
Labels: bug
